name: Playwright Tests

on:
  workflow_call:


jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      PETFINDER_KEY: ${{ secrets.PETFINDER_KEY }}
      PETFINDER_SECRET: ${{ secrets.PETFINDER_SECRET }}
      MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Install Playwright browsers
      run: bun x playwright install --with-deps

    - name: Run Playwright tests
      run: xvfb-run bun x playwright test

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-ui
        path: playwright-report/
        retention-days: 30
