name: Deploy to Vercel (Manual CLI)

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      VERCEL_ORG_ID: ${{ secrets.ORGID }}
      VERCEL_PROJECT_ID: ${{ secrets.PROJECTID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: npm run build

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
